logging:
  level:
    root: warn
    org.springframework.web: debug
    org.hibernate: error

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mybox
    username: example-user
    password: my_cool_secret

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always
